# Generated by Django 5.2.2 on 2025-06-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WniosekBudowlany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_zlozenia", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Złożony", "Złożony"),
                            ("W weryfikacji", "W weryfikacji"),
                            ("Zaakceptowany", "Zaakceptowany"),
                            ("Odrzucony", "Odrzucony"),
                        ],
                        default="Złożony",
                        max_length=20,
                    ),
                ),
                ("uzasadnienie_odrzucenia", models.TextField(blank=True, null=True)),
                ("rodzaj_inwestycji", models.CharField(max_length=200)),
                ("numer_dzialki", models.CharField(max_length=50)),
                (
                    "tytul",
                    models.CharField(
                        default="Wniosek o pozwolenie na budowę", max_length=255
                    ),
                ),
                ("opis_budowy", models.TextField()),
            ],
            options={
                "verbose_name": "Wniosek budowlany",
                "verbose_name_plural": "Wnioski budowlane",
            },
        ),
    ]
