# Generated by Django 5.2.2 on 2025-06-14 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ulica", models.CharField(max_length=100)),
                ("numer_domu", models.CharField(max_length=10)),
                (
                    "numer_mieszkania",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("kod_pocztowy", models.CharField(max_length=6)),
                ("miejscowosc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WniosekBudowlany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_zlozenia", models.DateTimeField(auto_now_add=True)),
                (
                    "powod_odrzucenia",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Powód odrzucenia (opcjonalnie)",
                    ),
                ),
                ("rodzaj_inwestycji", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Złożony", "Złożony"),
                            ("Zweryfikowany", "Zweryfikowany przez urzędnika"),
                            ("Zatwierdzony", "Zatwierdzony przez inspektora"),
                            ("Odrzucony", "Odrzucony"),
                        ],
                        default="Złożony",
                        max_length=50,
                    ),
                ),
                (
                    "adres_inwestycji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budownictwo.adres",
                    ),
                ),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_zlozenia"],
                "abstract": False,
            },
        ),
    ]
