# Generated by Django 5.2.2 on 2025-06-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budownictwo", "0001_initial"),
        ("ogolne", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wniosekbudowlany",
            name="powod_odrzucenia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="wniosekbudowlany",
            name="tytul",
            field=models.CharField(default="Tytul testowy", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wniosekbudowlany",
            name="adres_dzialki",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ogolne.adres"
            ),
        ),
        migrations.AlterField(
            model_name="wniosekbudowlany",
            name="data_zlozenia",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
