# Generated by Django 5.2.2 on 2025-06-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budownictwo", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wniosekbudowlany",
            options={
                "ordering": ["-data_zlozenia"],
                "verbose_name": "Wniosek budowlany",
                "verbose_name_plural": "Wnioski budowlane",
            },
        ),
    ]
