# Generated by Django 5.2.2 on 2025-06-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budownictwo", "0002_wniosekbudowlany_powod_odrzucenia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wniosekbudowlany",
            name="status",
            field=models.CharField(
                choices=[
                    ("oczekuje", "Oczekuje weryfikacji"),
                    ("zweryfikowany", "Zweryfikowany przez urzędnika"),
                    ("zatwierdzony", "Zatwierdzony przez inspektora"),
                    ("odrzucony", "Odrzucony"),
                ],
                default="oczekuje",
                max_length=20,
            ),
        ),
    ]
