# Generated by Django 5.2.2 on 2025-06-14 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeklaracjaSmieciowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Złożony", "Złożony"),
                            ("Zaakceptowany", "Zaakceptowany"),
                            ("Odrzucony", "Odrzucony"),
                        ],
                        default="Złożony",
                        max_length=50,
                    ),
                ),
                ("data_zlozenia", models.DateTimeField(auto_now_add=True)),
                (
                    "powod_odrzucenia",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Powód odrzucenia (opcjonalnie)",
                    ),
                ),
                ("adres_nieruchomosci", models.CharField(max_length=255)),
                ("liczba_mieszkancow", models.PositiveIntegerField()),
                (
                    "typ_zabudowy",
                    models.CharField(
                        choices=[
                            ("jednorodzinna", "Zabudowa jednorodzinna"),
                            ("wielorodzinna", "Zabudowa wielorodzinna"),
                        ],
                        max_length=20,
                    ),
                ),
                ("posiada_kompostownik", models.BooleanField(default=False)),
                (
                    "obliczona_oplata",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deklaracja śmieciowa",
                "verbose_name_plural": "Deklaracje śmieciowe",
            },
        ),
    ]
