# Generated by Django 5.2.2 on 2025-06-13 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeklaracjaSmieciowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liczba_osob", models.PositiveIntegerField()),
                (
                    "typ_zabudowy",
                    models.CharField(
                        choices=[
                            ("jednorodzinna", "Jednorodzinna"),
                            ("wielorodzinna", "Wielorodzinna"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="oczekuje", max_length=20)),
                (
                    "oplata",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("data_zlozenia", models.DateField(auto_now_add=True)),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
