# Generated by Django 5.2.2 on 2025-06-13 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ogolne", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZgloszenieUrodzenia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tytul", models.CharField(max_length=200)),
                ("data_zlozenia", models.DateTimeField(auto_now_add=True)),
                ("zatwierdzony", models.BooleanField(default=False)),
                ("powod_odrzucenia", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("oczekuje", "Oczekuje"),
                            ("zaakceptowane", "Zaakceptowane"),
                            ("odrzucone", "Odrzucone"),
                        ],
                        default="oczekuje",
                        max_length=13,
                    ),
                ),
                ("data_urodzenia", models.DateTimeField()),
                (
                    "mieszkaniec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ogolne.mieszkaniec",
                    ),
                ),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
