# Generated by Django 5.2.2 on 2025-06-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZgloszenieUrodzenia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_zlozenia", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Złożony", "Złożony"),
                            ("W weryfikacji", "W weryfikacji"),
                            ("Zaakceptowany", "Zaakceptowany"),
                            ("Odrzucony", "Odrzucony"),
                        ],
                        default="Złożony",
                        max_length=20,
                    ),
                ),
                ("uzasadnienie_odrzucenia", models.TextField(blank=True, null=True)),
                ("imie_dziecka", models.CharField(max_length=50)),
                ("nazwisko_dziecka", models.CharField(max_length=50)),
                (
                    "plec_dziecka",
                    models.CharField(
                        choices=[("M", "Mężczyzna"), ("K", "Kobieta")], max_length=10
                    ),
                ),
                ("data_urodzenia_dziecka", models.DateField()),
                ("miejsce_urodzenia_dziecka", models.CharField(max_length=100)),
                ("imie_matki", models.CharField(max_length=50)),
                ("nazwisko_rodowe_matki", models.CharField(max_length=50)),
                ("imie_ojca", models.CharField(max_length=50)),
                ("nazwisko_ojca", models.CharField(max_length=50)),
                (
                    "pesel_dziecka",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zgłoszenie urodzenia",
                "verbose_name_plural": "Zgłoszenia urodzeń",
            },
        ),
    ]
