# Generated by Django 5.2.2 on 2025-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dowody_osobiste", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wniosekdowod",
            options={
                "ordering": ["-data_zlozenia"],
                "verbose_name": "Wniosek o dowód osobisty",
                "verbose_name_plural": "Wnioski o dowód osobisty",
            },
        ),
        migrations.AddField(
            model_name="wniosekdowod",
            name="inny_powod_wydania",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Inny powód (proszę opisać)",
            ),
        ),
        migrations.AddField(
            model_name="wniosekdowod",
            name="zdjecie",
            field=models.ImageField(
                default="/media/zdjecie.png:", upload_to="zdjecia_dowodowe/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wniosekdowod",
            name="powod_wydania",
            field=models.CharField(
                choices=[
                    ("pierwszy_dowod", "Pierwszy dowód osobisty"),
                    ("utrata_dowodu", "Utrata lub uszkodzenie dowodu"),
                    ("zmiana_danych", "Zmiana danych zawartych w dowodzie"),
                    ("zmiana_wizerunku", "Zmiana wizerunku twarzy"),
                    ("uplyw_waznosci", "Upływ terminu ważności dowodu"),
                    ("uszkodzenie_dowodu", "Uszkodzenie dowodu"),
                    ("inny", "Inny powód"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="wniosekdowod",
            name="status",
            field=models.CharField(
                choices=[
                    ("Złożony", "Złożony"),
                    ("Przekazany do PWPW", "Przekazany do realizacji (PWPW)"),
                    ("Gotowy do odbioru", "Gotowy do odbioru w urzędzie"),
                    ("Odebrany", "Odebrany przez wnioskodawcę"),
                    ("Odrzucony", "Odrzucony"),
                ],
                default="Złożony",
                max_length=50,
            ),
        ),
    ]
