# Generated by Django 5.2.2 on 2025-06-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ulica", models.CharField(max_length=100)),
                ("numer_domu", models.CharField(max_length=10)),
                (
                    "numer_mieszkania",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("kod_pocztowy", models.CharField(max_length=6)),
                ("miejscowosc", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Adresy",
            },
        ),
        migrations.CreateModel(
            name="Mieszkaniec",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("pesel", models.CharField(max_length=11, unique=True)),
                ("data_urodzenia", models.DateField()),
                (
                    "plec",
                    models.CharField(
                        choices=[("M", "Mężczyzna"), ("K", "Kobieta")], max_length=1
                    ),
                ),
                ("imie_ojca", models.CharField(blank=True, max_length=50)),
                ("imie_matki", models.CharField(blank=True, max_length=50)),
                (
                    "adres_zameldowania",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mieszkancy_zameldowania",
                        to="ogolne.adres",
                    ),
                ),
                (
                    "adres_zamieszkania",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mieszkancy_zamieszkania",
                        to="ogolne.adres",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mieszkańcy",
            },
        ),
    ]
