# Generated by Django 5.2.2 on 2025-06-13 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ulica", models.CharField(max_length=100)),
                ("numer_domu", models.CharField(max_length=10)),
                ("kod_pocztowy", models.CharField(max_length=10)),
                ("miejscowosc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Mieszkaniec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=100)),
                ("nazwisko", models.CharField(max_length=100)),
                ("pesel", models.CharField(max_length=11, unique=True)),
                ("data_urodzenia", models.DateField()),
                ("data_zgonu", models.DateField(blank=True, null=True)),
                (
                    "plec",
                    models.CharField(
                        choices=[("M", "Mężczyzna"), ("K", "Kobieta")],
                        default="M",
                        max_length=1,
                        verbose_name="Płeć",
                    ),
                ),
                ("aktywny", models.BooleanField(default=True)),
                (
                    "adres",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mieszkancy",
                        to="ogolne.adres",
                    ),
                ),
                (
                    "matka",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dzieci_jako_matka",
                        to="ogolne.mieszkaniec",
                    ),
                ),
                (
                    "ojciec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dzieci_jako_ojciec",
                        to="ogolne.mieszkaniec",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_reverse",
                        to="ogolne.mieszkaniec",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
