# Generated by Django 5.2.2 on 2025-06-13 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecyzjaPodatkowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tytul", models.CharField(max_length=200)),
                ("kwota", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_wydania", models.DateField(auto_now_add=True)),
                (
                    "podatnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Decyzja podatkowa",
                "verbose_name_plural": "Decyzje podatkowe",
            },
        ),
        migrations.CreateModel(
            name="Wplata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kwota", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_wplaty", models.DateField(auto_now_add=True)),
                (
                    "decyzja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podatki.decyzjapodatkowa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wpłata",
                "verbose_name_plural": "Wpłaty",
            },
        ),
    ]
