# Generated by Django 5.2.2 on 2025-06-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecyzjaPodatkowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rok_podatkowy", models.PositiveIntegerField()),
                ("kwota", models.DecimalField(decimal_places=2, max_digits=10)),
                ("termin_platnosci", models.DateField()),
                ("oplacona", models.BooleanField(default=False)),
                (
                    "podatnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Decyzja podatkowa",
                "verbose_name_plural": "Decyzje podatkowe",
            },
        ),
        migrations.CreateModel(
            name="Wplata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_wplaty", models.DateField(auto_now_add=True)),
                ("kwota_wplaty", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "decyzja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wplaty",
                        to="podatki.decyzjapodatkowa",
                    ),
                ),
                (
                    "urzednik",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
