# Generated by Django 5.2.2 on 2025-06-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podatki", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wplata",
            options={"verbose_name": "Wpłata", "verbose_name_plural": "Wpłaty"},
        ),
    ]
