# Generated by Django 5.2.2 on 2025-06-15 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podatki", "0002_alter_wplata_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decyzjapodatkowa",
            options={
                "ordering": ["-data_wystawienia"],
                "verbose_name": "Decyzja podatkowa",
                "verbose_name_plural": "Decyzje podatkowe",
            },
        ),
        migrations.AddField(
            model_name="decyzjapodatkowa",
            name="data_wystawienia",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-08-17 14:26:39.482913+02:00"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="decyzjapodatkowa",
            name="podatnik",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decyzje_podatkowe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wplata",
            name="data_wplaty",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="wplata",
            name="urzednik",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zarejestrowane_wplaty",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="decyzjapodatkowa",
            unique_together={("podatnik", "rok_podatkowy")},
        ),
    ]
