# Generated by Django 5.2.2 on 2025-06-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatystykaLudnosci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(auto_now_add=True)),
                ("liczba_mieszkancow", models.PositiveIntegerField()),
                ("liczba_dzieci", models.PositiveIntegerField()),
                ("liczba_seniorow", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Statystyka ludności",
                "verbose_name_plural": "Statystyki ludności",
            },
        ),
    ]
