# Generated by Django 5.2.2 on 2025-06-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeklaracjaZbiornika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_zlozenia", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Złożony", "Złożony"),
                            ("W weryfikacji", "W weryfikacji"),
                            ("Zaakceptowany", "Zaakceptowany"),
                            ("Odrzucony", "Odrzucony"),
                        ],
                        default="Złożony",
                        max_length=20,
                    ),
                ),
                ("uzasadnienie_odrzucenia", models.TextField(blank=True, null=True)),
                (
                    "pojemnosc_zbiornika",
                    models.DecimalField(
                        decimal_places=2, help_text="Pojemność w m³", max_digits=6
                    ),
                ),
            ],
            options={
                "verbose_name": "Deklaracja posiadania zbiornika",
                "verbose_name_plural": "Deklaracje posiadania zbiorników",
            },
        ),
        migrations.CreateModel(
            name="DeklaracjaOproznienia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_zlozenia", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Złożony", "Złożony"),
                            ("W weryfikacji", "W weryfikacji"),
                            ("Zaakceptowany", "Zaakceptowany"),
                            ("Odrzucony", "Odrzucony"),
                        ],
                        default="Złożony",
                        max_length=20,
                    ),
                ),
                ("uzasadnienie_odrzucenia", models.TextField(blank=True, null=True)),
                ("data_oproznienia", models.DateField()),
                (
                    "ilosc_sciekow",
                    models.DecimalField(
                        decimal_places=2, help_text="Ilość w m³", max_digits=6
                    ),
                ),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deklaracja opróżnienia zbiornika",
                "verbose_name_plural": "Deklaracje opróżnienia zbiorników",
            },
        ),
    ]
