# Generated by Django 5.2.2 on 2025-06-14 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeklaracjaZbiornika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Złożony", "Złożony"),
                            ("Zaakceptowany", "Zaakceptowany"),
                            ("Odrzucony", "Odrzucony"),
                        ],
                        default="Złożony",
                        max_length=50,
                    ),
                ),
                ("data_zlozenia", models.DateTimeField(auto_now_add=True)),
                (
                    "powod_odrzucenia",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Powód odrzucenia (opcjonalnie)",
                    ),
                ),
                ("adres_nieruchomosci", models.CharField(max_length=255)),
                (
                    "pojemnosc_zbiornika",
                    models.DecimalField(
                        decimal_places=2, help_text="Pojemność w m³", max_digits=10
                    ),
                ),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deklaracja o posiadanym zbiorniku",
                "verbose_name_plural": "Deklaracje o posiadanych zbiornikach",
            },
        ),
        migrations.CreateModel(
            name="DeklaracjaOproznienia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Złożony", "Złożony"),
                            ("Zaakceptowany", "Zaakceptowany"),
                            ("Odrzucony", "Odrzucony"),
                        ],
                        default="Złożony",
                        max_length=50,
                    ),
                ),
                ("data_zlozenia", models.DateTimeField(auto_now_add=True)),
                (
                    "powod_odrzucenia",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Powód odrzucenia (opcjonalnie)",
                    ),
                ),
                ("data_oproznienia", models.DateField()),
                (
                    "ilosc_opadu",
                    models.DecimalField(
                        decimal_places=2, help_text="Ilość w m³", max_digits=10
                    ),
                ),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zbiornik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ewidencja_zbiornikow.deklaracjazbiornika",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deklaracja opróżnienia zbiornika",
                "verbose_name_plural": "Deklaracje opróżnienia zbiorników",
            },
        ),
    ]
