# Generated by Django 5.2.2 on 2025-06-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ewidencja_zbiornikow", "0001_initial"),
        ("ogolne", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deklaracjazbiornika",
            name="adres_nieruchomosci",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ogolne.adres"
            ),
        ),
        migrations.AddField(
            model_name="deklaracjazbiornika",
            name="wnioskodawca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="deklaracjaoproznienia",
            name="deklaracja_zbiornika",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ewidencja_zbiornikow.deklaracjazbiornika",
            ),
        ),
    ]
