# Generated by Django 5.2.2 on 2025-06-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ewidencja_zbiornikow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deklaracjaoproznienia",
            name="status",
        ),
        migrations.RemoveField(
            model_name="deklaracjaoproznienia",
            name="zatwierdzony",
        ),
        migrations.RemoveField(
            model_name="deklaracjazbiornika",
            name="status",
        ),
        migrations.RemoveField(
            model_name="deklaracjazbiornika",
            name="zatwierdzony",
        ),
    ]
