# Generated by Django 5.2.2 on 2025-06-13 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WniosekDotacja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tytul", models.CharField(max_length=200)),
                ("opis", models.TextField()),
                ("kwota", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("oczekuje", "Oczekuje"),
                            ("zaakceptowany_komisja", "Zaakceptowany przez komisję"),
                            ("odrzucony_komisja", "Odrzucony przez komisję"),
                            ("zatwierdzony_wojt", "Zatwierdzony przez wójta"),
                            ("odrzucony_wojt", "Odrzucony przez wójta"),
                            ("zrealizowany", "Zrealizowany"),
                        ],
                        default="oczekuje",
                        max_length=30,
                    ),
                ),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
