# Generated by Django 5.2.2 on 2025-06-14 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WniosekDotacja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Złożony", "Złożony"),
                            ("Zaakceptowany", "Zaakceptowany"),
                            ("Odrzucony", "Odrzucony"),
                        ],
                        default="Złożony",
                        max_length=50,
                    ),
                ),
                ("data_zlozenia", models.DateTimeField(auto_now_add=True)),
                (
                    "powod_odrzucenia",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Powód odrzucenia (opcjonalnie)",
                    ),
                ),
                ("tytul_projektu", models.CharField(max_length=255)),
                ("opis_projektu", models.TextField()),
                (
                    "wnioskowana_kwota",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wniosek o dotację",
                "verbose_name_plural": "Wnioski o dotacje",
            },
        ),
    ]
