# Generated by Django 5.2.2 on 2025-06-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dotacje", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wniosekdotacja",
            options={
                "ordering": ["-data_zlozenia"],
                "verbose_name": "Wniosek o dotację",
                "verbose_name_plural": "Wnioski o dotacje",
            },
        ),
        migrations.AlterField(
            model_name="wniosekdotacja",
            name="status",
            field=models.CharField(
                choices=[
                    ("Złożony", "Złożony"),
                    ("Do oceny komisji", "Przekazany do oceny komisji"),
                    ("Do decyzji wójta", "Oczekuje na decyzję wójta"),
                    ("Zatwierdzony", "Zatwierdzony przez wójta"),
                    ("Do realizacji (Skarbnik)", "Oczekuje na przelew skarbnika"),
                    ("Zrealizowany", "Dotacja wypłacona"),
                    ("Odrzucony", "Odrzucony"),
                    ("Braki formalne", "Wezwanie do uzupełnienia braków"),
                ],
                default="Złożony",
                max_length=50,
            ),
        ),
    ]
