# Generated by Django 5.2.2 on 2025-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dotacje", "0002_alter_wniosekdotacja_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wniosekdotacja",
            name="status",
            field=models.CharField(
                choices=[
                    ("Złożony", "Złożony"),
                    ("Do oceny komisji", "Przekazany do oceny komisji"),
                    ("Do decyzji wójta", "Oczekuje na decyzję wójta"),
                    ("Zatwierdzony", "Zatwierdzony przez wójta"),
                    ("Do realizacji (Skarbnik)", "Oczekuje na przelew skarbnika"),
                    ("Zrealizowany", "Dotacja wypłacona"),
                    ("Odrzucony", "Odrzucony"),
                ],
                default="Złożony",
                max_length=50,
            ),
        ),
    ]
