# Generated by Django 5.2.2 on 2025-06-15 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dotacje", "0003_alter_wniosekdotacja_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="wniosekdotacja",
            name="numer_konta_bankowego",
            field=models.CharField(
                default=1234567890123456789012,
                help_text="Proszę podać 26-cyfrowy numer konta bankowego (bez spacji i myślników).",
                max_length=26,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{26}$", "Numer konta musi składać się z 26 cyfr."
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
