# Generated by Django 5.2.2 on 2025-06-13 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WniosekRejestracjaSamochodu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("numer_rejestracyjny", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("oczekuje", "Oczekuje"),
                            ("zatwierdzony", "Zatwierdzony"),
                            ("odrzucony", "Odrzucony"),
                        ],
                        default="oczekuje",
                        max_length=20,
                    ),
                ),
                ("data_zlozenia", models.DateField(auto_now_add=True)),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wniosek o rejestrację samochodu",
                "verbose_name_plural": "Wnioski o rejestrację samochodu",
            },
        ),
    ]
