# Generated by Django 5.2.2 on 2025-06-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WniosekRejestracja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_zlozenia", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Złożony", "Złożony"),
                            ("W weryfikacji", "W weryfikacji"),
                            ("Zaakceptowany", "Zaakceptowany"),
                            ("Odrzucony", "Odrzucony"),
                        ],
                        default="Złożony",
                        max_length=20,
                    ),
                ),
                ("uzasadnienie_odrzucenia", models.TextField(blank=True, null=True)),
                ("marka_pojazdu", models.CharField(max_length=100)),
                ("model_pojazdu", models.CharField(max_length=100)),
                ("rok_produkcji", models.PositiveIntegerField()),
                ("numer_vin", models.CharField(max_length=17, unique=True)),
                (
                    "numer_rejestracyjny",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "wnioskodawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wniosek o rejestrację samochodu",
                "verbose_name_plural": "Wnioski o rejestrację samochodów",
            },
        ),
    ]
